# Generated by Django 3.1.5 on 2021-01-08 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_open', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('buy_price', models.FloatField()),
                ('date_closed', models.DateTimeField()),
                ('sell_price', models.FloatField()),
                ('Loss_Profit', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(choices=[('XRP', 'XRP'), ('ETH', 'Ethereum')], max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
