# Generated by Django 3.1.5 on 2021-01-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_auto_20210109_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vc',
            name='loss_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vc',
            name='sell_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
